[workspace]
resolver = "3"
members = [
    "examples/rust/dioxus",
    "crates/wf-observer-cli",
    "crates/memory-reader",
    "crates/protocol",
    "crates/wf-observer",
    "crates/wf-observer-ffi",
    "xtask",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# Memflow + Memflow native deps live in crates/memory-reader

tokio = { version = "1.53.1", default-features = false }
tokio-util = { version = "0.7.18", default-features = false }
iroh = {
    version = "1.0",
    default-features = false,
    features = ["tls-ring"],
}
iroh-tickets = { version = "1.0" }
irpc = { version = "0.17" }
irpc-iroh = { version = "0.17" }
getrandom = { version = "0.4.3", default-features = false }

# FFI
boltffi = { version = "=0.30.1", default-features = false }

# Local application deps
clap = { version = "4.6" }
clap-verbosity-flag = { version = "3.0.4", default-features = false, features = ["tracing"] }

# Serialisation
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
postcard = { version = "1.1", default-features = false, features = ["use-std"] }

# Logging / Errors
anyhow = { version = "1.0" }
thiserror = { version = "2.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }

# Misc Helpers
directories = { version = "6" }
itertools = { version = "0.15" }
tempfile = { version = "3.23" }
pollster = { version = "1.0.1" }
semver = { version = "1.0" }
sysinfo = { version = "0.39", default-features = false, features = ["system"] }
rustix = { version = "1.1", default-features = false }
windows-sys = { version = "0.61", default-features = false }

# Boilerplate Helpers
displaydoc = { version = "0.2" }
derive_more = { version = "2.1" }
derive_aliases = { version = "0.4" }

# Performance optimizations
parking_lot = { version = "0.12" }
fastant = { version = "0.1" }
hotpath = { version = "0.24" }

# Some dependencies can spam this causing perf issues.
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "deny"
unimplemented = "deny"
disallowed_types = "deny"
disallowed_methods = "deny"

# Optimisations for the dev profile.
# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Optimize for build time in CI.
[profile.ci]
inherits = "dev"
opt-level = 0
debug = "line-tables-only"
incremental = false

[profile.ci.package."*"]
opt-level = 0
debug = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "debuginfo"
panic = "unwind"

