[package]
name = "wf-observer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
protocol = { path = "../protocol" }

derive_aliases = { workspace = true }
serde = { workspace = true }

anyhow = { workspace = true }
iroh = { workspace = true }
irpc = { workspace = true }
irpc-iroh = { workspace = true }
hotpath = { workspace = true }

[lints]
workspace = true
