[package]
name = "wf-observer-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "wf-observer"
path = "src/main.rs"
doc = false

[dependencies]
memory-reader = { path = "../memory-reader" }
protocol = { path = "../protocol" }

tokio = { workspace = true, features = ["full"] }
iroh = { workspace = true, features = ["portmapper"] }
iroh-tickets = { workspace = true }
irpc = { workspace = true }
irpc-iroh = { workspace = true }

clap = { workspace = true, features = ["derive"] }
clap-verbosity-flag = { workspace = true }
derive_aliases = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
directories = { workspace = true }
tempfile = { workspace = true }

hotpath = { workspace = true, features = ["tokio"] }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["process"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_System_Threading"] }

[dev-dependencies]
wf-observer = { path = "../wf-observer" }
wf_observer_ffi = { path = "../wf-observer-ffi" }

[lints]
workspace = true
