[package]
name = "local-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
memory-reader = { path = "../memory-reader" }
protocol = { path = "../protocol" }

tokio = { workspace = true }
hotpath = { workspace = true }

[features]
# For Profiling
hotpath = ["hotpath/hotpath"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

[lints]
workspace = true
